### ISSUE TITLE
Last branch of case expression omitted from PPAst

### ISSUE THREAD

**Issue by JohnReppy** [smlnj/smlnj#205]
### Version

v110.98

### Operating System

- [ ] All
- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### OS Version

Ubuntu 18.04

### Component

Core system

### Severity

Minor

### Description of the problem

When printing a `CaseExp` using `PPAst`, the last branch is omitted from printing.

One potential fix would be to remove the `trim` function, using `rules` instead of `trim rules`. (I'm not sure what the reasoning behind `trim` is in the first place, though.)

### Transcript

```
- val pd : PrettyPrint.device = {consumer = print, linewidth = Fn.const 80, flush = fn () => TextIO.flushOut TextIO.stdOut};
val pd = {consumer=fn,flush=fn,linewidth=fn} : ?.PrettyPrint.PP.device
- val dec = SmlFile.parse (Source.newSource ("demo", TextIO.openString "case 0 of 0 => 0", false, ErrorMsg.defaultConsumer ()));
val dec =
  SeqDec
    [MarkDec
       (ValDec ([Vb {exp=MarkExp #,lazyp=false,pat=VarPat #}],[]),(2,18))]
  : Ast.dec
- let val strm = PrettyPrint.openStream pd in PPAst.ppDec NONE strm (dec,6) before PrettyPrint.closeStream strm end;
val it =
      (case 0
      )val it = () : unit
```

### Steps to Reproduce

val pd : PrettyPrint.device = {consumer = print, linewidth = Fn.const 80, flush = fn () => TextIO.flushOut TextIO.stdOut};
val dec = SmlFile.parse (Source.newSource ("demo", TextIO.openString "case 0 of 0 => 0", false, ErrorMsg.defaultConsumer ()));
let val strm = PrettyPrint.openStream pd in PPAst.ppDec NONE strm (dec,6) before PrettyPrint.closeStream strm end;

#### Original smlnj-gforge bug number 270

Submitted  on 2020-35-08 at 21:3500

**Keywords:** pretty-print

**Comment by dmacqueen** [comment]
This bug is fixed for 110.99.3.  The cause was a call of trim on the list of cases in an act case expression, which was originally included because the last rule of a case was an artificial additional rule that would raise the Match exception in cases where the preceding rules did not match.  This is no longer necessary in Legacy or Trunk ("development"), so that call of trim, and the trim function itself, have been deleted.
