### ISSUE TITLE
Web site smlnj.org: A hyperlink to the "not found page"

### ISSUE THREAD

**Issue by haijinSk** [smlnj/smlnj#253]
### Version

2021.1

### Operating System

- [x] Any
- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### Processor

- [x] Any
- [ ] Arm (using Rosetta)
- [ ] x86-64 (64-bit)
- [ ] Other

### System Component

Installation

### Severity

Cosmetic

### Description

The "404 not found link" is on the page: https://www.smlnj.org/dist/working/2021.1/ 

In the first section, Linux (64 bits),  the second link: [install.html](https://www.smlnj.org/dist/working/2021.1/install.html) 

### Steps to Reproduce

Click on the link: https://www.smlnj.org/dist/working/2021.1/install.html

**Comment by JohnReppy** [comment]
The `install.html` file never got copied to the distribution directory.  It is there now, so I'm closing this issue.
