### ISSUE TITLE
Some minor suggestions to the `README` file

### ISSUE THREAD

**Issue by cr2007** [smlnj/smlnj#255]
### Description

I wanted to suggest a couple of changes to the `README.md` file to make it easier for users coming for the first time to have an eagle's eye view of the repository before going through the other files and directories.

Here are the suggestions:
- Adding an **Index** at the top before listing the key steps (i.e. Building From Source, Recompiling, etc.)
- Adding hyperlinks to the files, directories mentioned in the steps
(i.e. from `build.sh` to [`build.sh`](https://github.com/smlnj/smlnj/blob/main/build.sh) (won't be direct URLs, but the relative file path)

**Comment by JohnReppy** [comment]
I've merged the pull requests.  I changed "Index" to "Contents".
