### ISSUE TITLE
Copyright Inconsistency, "no commercial product" in libraries/ckit/src/parser/util/error.sml

### ISSUE THREAD

**Issue by barak** [smlnj/smlnj#258]
### Version

2021.1

### Operating System

- [X] Any
- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### Processor

- [X] Any
- [ ] Arm (using Rosetta)
- [ ] x86-64 (64-bit)
- [ ] Other

### System Component

Other

### Severity

Major

### Description

There's an inconsistency between the top-level `LICENSE` file, which is free, versus the files

* `libraries/ckit/src/parser/util/error-sig.sml`
* `libraries/ckit/src/parser/util/error.sml`

which state:
```
 * Copyright (c) 1996 by Satish Chandra, Brad Richards, Mark D. Hill, 
 * James R. Larus, and David A. Wood.
 *
 * Teapot is distributed under the following conditions:
 * 
 *     You may make copies of Teapot for your own use and modify those copies.
 * 
 *     All copies of Teapot must retain our names and copyright notice.
 * 
 *     You may not sell Teapot or distributed Teapot in conjunction with a
 *     commercial product or service without the expressed written consent of
 *     the copyright holders.
 * 
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
```
Note in particular the **may not sell Teapot or distributed Teapot in conjunction with a commercial product or service without the expressed written consent of the copyright holders.** This clause has gotten `smlnj` pulled from Debian testing, and when other distributions notice they will probably follow suit.

### Steps to Reproduce

This can be reproduced by inspection.

### Email address

Barak A. Pearlmutter <barak@pearlmutter.net>

**Comment by JohnReppy** [comment]
Thanks for pointing out this discrepancy.

If you look a bit further down the file, you see

``` sml
* CS703 --- Project --- Spring '94
```

That was a course that I taught while visiting the University of Wisconsin in 1994 (Satish was a student in the class).  The original code was actually mine.  I'm not sure why/how CKit got it from Teapot, except that I think Satish may have worked on CKit when he was at Bell Labs.  Anyway, I think that we can safely update the header comment.

**Comment by barak** [comment]
Excellent, thanks. That was fast!

The version of smlnj in Debian is ancient, but in order to avoid letting the perfect be the enemy of the good, I'll backport this copyright fix, and then try to push a more up-to-date version.
