### ISSUE TITLE
The new version doesn't seem to support windows right now.

### ISSUE THREAD

**Issue by fenginsc** [smlnj/smlnj#259]
### Version

2021.1

### Operating System

- [ ] Any
- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Other Unix

### OS Version

windows10

### Processor

- [ ] Any
- [ ] Arm (using Rosetta)
- [X] x86-64 (64-bit)
- [ ] Other

### System Component

Installation

### Severity

Major

### Description

The new version doesn't seem to support windows right now.
Older versions are supported such as 110.99.3.

### Steps to Reproduce

none.

### Email address

fyjzyyx@gmail.com

**Comment by JohnReppy** [comment]
This is correct and documented.  For Windows, you should use the legacy branch (110.99.3 is the latest version).  We will support Windows with the main development branch in the future, but probably not before the end of next Summer.
