### ISSUE TITLE
Installation of SML/NJ 2023.1 on macOS 14 with M1 hardware fails

### ISSUE THREAD

**Issue by HarrisonGrodin** [smlnj/smlnj#283]
### Version

2023.1 (latest)

### Operating System

- [ ] Any
- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Other Unix

### OS Version

macOS 14 (Sonoma)

### Processor

- [ ] Any
- [X] Arm (using Rosetta)
- [ ] x86-64 (64-bit)
- [ ] Other

### System Component

Installation

### Severity

Critical

### Description

Installation on macOS 14 with an M1 fails; tested in a clean environment via GitHub Actions, following the instructions (in #ProjectSavanna/setup-sml#129).

This may have something to do with file naming on macOS, amd64 vs arm64?

### Transcript

Following lots of seemingly-successful installation information:
```
cleaning codegen
rm -f v-* *.o libcodegen.a
rm -f v-* *.o
(cd ../gc; make MAKE="make" clean)
rm -f v-* *.o libgc.a
+++++ CODE WRITE
----- CODE WRITE
+++++ CODE WRITE
----- CODE WRITE
+++++ CODE WRITE
----- CODE WRITE
+++++ CODE WRITE
----- CODE WRITE
/Users/runner/work/setup-sml/setup-sml/smlnj/build.sh: line 447: 27387 Segmentation fault: 11  "$BINDIR"/.link-sml @SMLheap="$SMLNJ_ROOT"/sml @SMLboot=BOOTLIST @SMLalloc=$ALLOC
/Users/runner/work/setup-sml/setup-sml/smlnj/build.sh: !!! Boot code failed, no heap image (sml.arm64-darwin).
Error: The process '/Users/runner/work/setup-sml/setup-sml/smlnj/build.sh' failed with exit code 1
```

### Steps to Reproduce

Install SML/NJ 2023.1 on macOS 14 with M1.

**Comment by JohnReppy** [comment]
Currently, the only support for macOS/Apple Silicon is 110.99.5 running on Rosetta.  We are working on the Arm port for  the development version, but it has turned out to be challenging.
