### ISSUE TITLE
2023.1 files are missing from smlnj.org

### ISSUE THREAD

**Issue by HarrisonGrodin** [smlnj/smlnj#286]
### Version

2023.1 (latest)

### Operating System

- [X] Any
- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### System Component

Installation

### Severity

Critical

### Description

It seems that all links to SML/NJ 2023.1 have disappeared, and installing in the way that used to work now breaks. https://smlnj.org/dist/working/2023.1/index.html

### Transcript

Not Found
The requested URL was not found on this server.

Apache/2.4.52 (Ubuntu) Server at smlnj.org Port 443

### Steps to Reproduce

Open https://smlnj.org/dist/working/2023.1/index.html or attempt to install 2023.1 as before.

**Comment by JohnReppy** [comment]
We had a problem a few weeks ago where a lot of files got deleted (including 2023.1).  I thought that everything had been restored, but I guess 2023.1 was not.  I'll have to see if there is still a backup somewhere.

BTW, I was planning on putting out 2024.1 soon, which will have all of the 110.99.5 improvements.

**Comment by dmacqueen** [comment]
"Summary description of bug #286" is not a very useful "title" for this bug issue. Is there a way of changing the title of an issue?

Presumably if there is a supported process for creating a bug issue, one of the things that that process should include is selecting an appropriate title for the issue.  But is there such a bug reporting process, and if so, where is it documented?

**Comment by JohnReppy** [comment]
The title was the placeholder text from the issue template.  I've changed it, which you can do by clicking the "Edit" button to the right of the title.

**Comment by JohnReppy** [comment]
The files have been restored.
