### ISSUE TITLE
NJ 2024.1 and 2024.2 fail to install on macOS 14

### ISSUE THREAD

**Issue by HarrisonGrodin** [smlnj/smlnj#290]
### Version

2024.1 (latest)

### Operating System

- [ ] Any
- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Other Unix

### OS Version

macOS 14 (Sonoma)

### System Component

Installation

### Severity

Critical

### Description

When testing the installation of SML/NJ versions in `setup-sml`, I noticed that 2024.1 and 2024.2 [fail to install on macOS 14](https://github.com/ProjectSavanna/setup-sml/actions/runs/10375364074/job/28724996170) (although they have no problems on Ubuntu and macOS 12-13).

I can't tell what the issue is, but it seems to be early on the installation. With macOS 13, I get:
```
Updating files: 100% (4680/4680)
Updating files: 100% (4680/4680), done.
Submodule 'runtime/llvm' (https://github.com/smlnj/smlnj-llvm-10.git) registered for path 'runtime/llvm'
Cloning into '/Users/runner/work/setup-sml/setup-sml/smlnj/runtime/llvm'...
Submodule path 'runtime/llvm': checked out '1a58ba4028a205f22d8dc394cbb67d10ea649823'
/Users/runner/work/setup-sml/setup-sml/smlnj/build.sh
build-llvm.sh: mkdir build
```
where after the clone, it starts installing (and then installs for another ~25m). On macOS 14, though, it finishes the clone and never prints anything after the `100%` line. So, maybe it's an issue with installing LLVM on macOS 14?

### Transcript

```
/opt/homebrew/bin/git clone --depth 1 --branch v2024.1 --recurse-submodules https://github.com/smlnj/smlnj.git
Cloning into 'smlnj'...
Updating files:  79% (10214/12843)
Updating files:  80% (10275/12843)
Updating files:  81% (10403/12843)
Updating files:  82% (10532/12843)
Updating files:  83% (10660/12843)
Updating files:  84% (10789/12843)
Updating files:  85% (10917/12843)
Updating files:  86% (11045/12843)
Updating files:  87% (11174/12843)
Updating files:  88% (11302/12843)
Updating files:  89% (11431/12843)
Updating files:  90% (11559/12843)
Updating files:  91% (11688/12843)
Updating files:  92% (11816/12843)
Updating files:  93% (11944/12843)
Updating files:  94% (12073/12843)
Updating files:  95% (12201/12843)
Updating files:  96% (12330/12843)
Updating files:  97% (12458/12843)
Updating files:  98% (12587/12843)
Updating files:  99% (12715/12843)
Updating files: 100% (12843/12843)
Updating files: 100% (12843/12843), done.
```
Then, the process exits with failure.

### Steps to Reproduce

Attempt to install SML/NJ 2024.1 on macOS 14.

**Comment by JohnReppy** [comment]
Can you explain what `setup-sml` is and what it is doing?  I'm able to build a fresh copy of 2024.1 (and 2024.2) on my Intel iMac (macOS 14.6.1) without any problems using the following commands:

``` console
git clone --depth 1 --branch v2024.1 --recurse-submodules https://github.com/smlnj/smlnj.git 2024.1
cd 2024.1
curl -O https://smlnj.org/dist/working/2024.1/boot.amd64-unix.tgz
build.sh
```

**Comment by HarrisonGrodin** [comment]
Aha - it looks like it was set to download `arm64-unix.tgz`, not `amd64-unix.tgz`, since it was running on an M1 machine; however, this download 404's. (I'm not sure where this came from - perhaps that URL used to be mentioned in the installation instructions but was changed? It seems like I added this distinction to test on M1 in the first place, ProjectSavanna/setup-sml#129, and it seems like it used to work then.)

I removed this check/always download `amd64` in ProjectSavanna/setup-sml#146, and now the installation proceeds. However, towards the end, it now gives this error:
```
cleaning codegen
rm -f v-* *.o libcodegen.a
rm -f v-* *.o
(cd ../gc; make MAKE="make" clean)
rm -f v-* *.o libgc.a
/Users/runner/work/setup-sml/setup-sml/smlnj/build.sh: !!! Missing boot.arm64-unix.tgz
Error: The process '/Users/runner/work/setup-sml/setup-sml/smlnj/build.sh' failed with exit code 1
```

It seems like `arm64-unix.tgz` may be required after all?

**Comment by JohnReppy** [comment]
Because I've been working on native Arm support in the development version of SML/NJ, it does not support bootstrapping on Arm using Rosetta2.  The legacy version does support bootstrapping under Rosetta (thanks
to Byron Zhong), but I suspect that it is a bit harder to make that work in the development branch.
